import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: "#F0F4F8",
    },
    header: {
        height: height * 0.4,
    },
    headerImage: {
        flex: 1,
        width: '100%',
    },
    darkOverlay: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: "rgba(23,40,93,0.7)",
    },
    headerContent: {
        flex: 1,
        justifyContent: 'flex-end',
        padding: 24,
    },
    difficultyContainer: {
        marginBottom: 16,
    },
    difficultyBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 12,
        backgroundColor: '#27AE60',
        alignSelf: 'flex-start',
    },
    difficultyIcon: {
        fontSize: 12,
        marginRight: 6,
    },
    difficultyText: {
        fontSize: 12,
        fontFamily: "Poppins_700Bold",
        color: "#FFFFFF",
        textTransform: 'uppercase',
    },
    gameTitle: {
        fontSize: 32,
        fontFamily: "Poppins_700Bold",
        color: "#FFFFFF",
        marginBottom: 8,
        textShadowColor: 'rgba(0, 0, 0, 0.3)',
        textShadowOffset: { width: 1, height: 1 },
        textShadowRadius: 4,
    },
    gameCategory: {
        fontSize: 16,
        fontFamily: "Poppins_400Regular",
        color: "rgba(255,255,255,0.9)",
        textTransform: 'uppercase',
        letterSpacing: 1,
    },
    content: {
        flex: 1,
    },
    contentInner: {
        padding: 24,
        paddingBottom: 120,
    },
    section: {
        marginBottom: 32,
    },
    sectionHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 16,
    },
    sectionTitle: {
        fontSize: 16,
        fontFamily: "Poppins_700Bold",
        color: "#17285D",
        marginLeft: 8,
        letterSpacing: 1,
    },
    description: {
        fontSize: 16,
        fontFamily: "Poppins_400Regular",
        color: "#4A6FA5",
        lineHeight: 24,
        textAlign: 'justify',
    },
    benefitsGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        marginHorizontal: -6,
    },
    benefitItem: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: "#E8EEF4",
        paddingHorizontal: 12,
        paddingVertical: 8,
        borderRadius: 12,
        margin: 6,
        borderWidth: 1,
        borderColor: "#D8E2EC",
    },
    benefitText: {
        fontSize: 14,
        fontFamily: "Poppins_600SemiBold",
        color: "#17285D",
        marginLeft: 6,
    },
    infoCard: {
        backgroundColor: "#FFFFFF",
        borderRadius: 20,
        padding: 20,
        marginBottom: 24,
        shadowColor: "#17285D",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.1,
        shadowRadius: 12,
        elevation: 4,
        borderWidth: 1,
        borderColor: "#E8EEF4",
    },
    infoItem: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 8,
    },
    infoContent: {
        marginLeft: 12,
        flex: 1,
    },
    infoLabel: {
        fontSize: 12,
        fontFamily: "Poppins_600SemiBold",
        color: "#4A6FA5",
        textTransform: 'uppercase',
        letterSpacing: 1,
    },
    infoValue: {
        fontSize: 16,
        fontFamily: "Poppins_700Bold",
        color: "#17285D",
        marginTop: 2,
    },
    infoSeparator: {
        height: 1,
        backgroundColor: "#E8EEF4",
        marginVertical: 8,
    },
    tipCard: {
        flexDirection: 'row',
        backgroundColor: "rgba(243, 156, 18, 0.1)",
        borderRadius: 16,
        padding: 16,
        borderLeftWidth: 4,
        borderLeftColor: "#F39C12",
    },
    tipContent: {
        flex: 1,
        marginLeft: 12,
    },
    tipTitle: {
        fontSize: 14,
        fontFamily: "Poppins_700Bold",
        color: "#17285D",
        marginBottom: 4,
    },
    tipText: {
        fontSize: 14,
        fontFamily: "Poppins_400Regular",
        color: "#4A6FA5",
        lineHeight: 20,
    },
    footer: {
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        backgroundColor: "#F0F4F8",
        padding: 24,
        paddingBottom: 34,
        borderTopWidth: 1,
        borderTopColor: "#E8EEF4",
    },
    primaryButton: {
        backgroundColor: "#4A6FA5",
        borderRadius: 25,
        marginBottom: 12,
        shadowColor: "#17285D",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        elevation: 6,
    },
    buttonContent: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 18,
        paddingHorizontal: 32,
    },
    primaryButtonText: {
        fontSize: 18,
        fontFamily: "Poppins_700Bold",
        color: "#FFFFFF",
        marginLeft: 8,
    },
    secondaryButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: "transparent",
        paddingVertical: 16,
        paddingHorizontal: 32,
        borderRadius: 25,
        borderWidth: 2,
        borderColor: "#4A6FA5",
    },
    secondaryButtonText: {
        fontSize: 16,
        fontFamily: "Poppins_600SemiBold",
        color: "#4A6FA5",
        marginLeft: 8,
    },
});