import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    background: {
        flex: 1,
        width: '100%',
        height: '100%',
    },
    overlay: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        paddingHorizontal: 20,
    },
    card: {
        width: '90%',
        backgroundColor: '#F0F0F0',
        borderRadius: 20,
        paddingVertical: 30,
        paddingHorizontal: 25,
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 5,
        elevation: 5,
    },
    logo: {
        width: 200,
        height: 175,
        resizeMode: 'contain',
        marginBottom: 10,
    },
    title: {
        fontSize: 22,
        fontFamily: 'Poppins_700Bold',
        color: '#333',
        marginBottom: 25,
        textAlign: 'center',
    },
    allinput: {
        width: '100%',
        alignItems: 'center',
        marginBottom: 25,
    },
    inputContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#fff',
        borderRadius: 10,
        width: '100%',
        height: 50,
        paddingHorizontal: 15,
        marginBottom: 15,
        borderColor: '#17285D',
        borderWidth: 1,
    },
    input: {
        flex: 1,
        fontFamily: 'Poppins_400Regular',
        fontSize: 16,
        color: '#333',
    },
    iconContainer: {
        marginLeft: 10,
        justifyContent: 'center',
        alignItems: 'center',
    },
    button: {
        backgroundColor: '#8ec0c7',
        borderRadius: 12,
        paddingVertical: 14,
        paddingHorizontal: 50,
        elevation: 2,
        borderColor: '#17285D',
        borderWidth: 1,
    },
    buttonText: {
        color: '#17285D',
        fontSize: 16,
        textAlign: 'center',
        fontFamily: 'Poppins_700Bold',
    },
});
