import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: "#f2f2f2",
        fontFamily: "Poppins_400Regular",
    },
    content: {
        padding: 20,
        alignItems: "center",
    },
    avatarContainer: {
        alignItems: "center",
        marginBottom: 20,
    },
    avatar: {
        width: 120,
        height: 120,
        borderRadius: 60,
        marginBottom: 10,
        marginTop: 20,
    },
    nome: {
        fontSize: 20,
        fontFamily: "Poppins_700Bold",
    },
    email: {
        fontSize: 14,
        color: "gray",
        marginTop: -5,
        marginBottom: 10,
        fontFamily: "Poppins_400Regular",
    },
    card: {
        width: "100%",
        backgroundColor: "#fff",
        borderRadius: 15,
        padding: 20,
        marginBottom: 15,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 3 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    cardTitle: {
        fontSize: 16,
        fontFamily: "Poppins_700Bold",
        marginBottom: 10,
    },
    actions: {
        width: "100%",
        flexDirection: "row",
        justifyContent: "space-around",
        marginTop: 20,
        marginBottom: 40,
    },
    button: {
        paddingVertical: 12,
        paddingHorizontal: 30,
        borderRadius: 25,
    },
    logoutButton: {
        backgroundColor: "#5C172C", // #E74C3C",
    },
    buttonText: {
        color: "#fff",
        fontFamily: "Poppins_700Bold",
        fontSize: 16,
    },
    smallButton: {
        marginTop: 8,
        paddingVertical: 8,
        paddingHorizontal: 14,
        backgroundColor: "#17285D",
        borderRadius: 8,
        alignSelf: "center",
    },
    smallButtonText: {
        color: "#fff",
        fontFamily: "Poppins_400Regular",
    },
    section: {
        marginTop: 20,
        marginHorizontal: 20,
        padding: 15,
        backgroundColor: "#fff",
        borderRadius: 15,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 2,
        
    },
    sectionTitle: {
        fontSize: 16,
        fontFamily: "Poppins_700Bold",
        marginBottom: 5,
    },
    placeholder: {
        fontStyle: "italic",
        color: "gray",
    },
    sectionContent: {
        fontSize: 14,
        marginBottom: -4,
        fontFamily: "Poppins_400Regular",
    },
    avatarsModalOverlay: {
        flex: 1,
        backgroundColor: "rgba(0,0,0,0.5)",
        justifyContent: "center",
        alignItems: "center",
    },
    avatarsModal: {
        width: "90%",
        backgroundColor: "#fff",
        borderRadius: 15,
        padding: 20,
    },
    avatarsGrid: {
        marginTop: 12,
        flexDirection: "row",
        flexWrap: "wrap",
        justifyContent: "space-between",
    },
    avatarOption: {
        width: "48%",
        aspectRatio: 1,
        borderRadius: 12,
        overflow: "hidden",
        marginBottom: 10,
        borderWidth: 1,
        borderColor: "#e0e0e0",
    },
    avatarOptionImage: {
        width: "100%",
        height: "100%",
    },
    closeModalButton: {
        marginTop: 8,
        alignSelf: "center",
        paddingVertical: 8,
        paddingHorizontal: 14,
        backgroundColor: "#e0e0e0",
        borderRadius: 8,
    },
});
