import { StyleSheet, Dimensions } from "react-native";

const { width } = Dimensions.get('window');

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: "#f8fafc",
        fontFamily: "Poppins_400Regular",
    },
    header: {
        alignItems: "center",
        paddingVertical: 30,
        paddingHorizontal: 20,
        backgroundColor: "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",
        borderBottomLeftRadius: 30,
        borderBottomRightRadius: 30,
        marginBottom: 20,
    },
    avatarWrapper: {
        position: 'relative',
        alignItems: 'center',
        marginBottom: 15,
    },
    avatar: {
        width: 120,
        height: 120,
        borderRadius: 60,
        borderWidth: 2,
        borderColor: "#17285D",
        marginBottom: -15,
    },
    editAvatarButton: {
        position: 'absolute',
        bottom: 5,
        right: 5,
        backgroundColor: '#17285D',
        width: 36,
        height: 36,
        borderRadius: 18,
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 3,
        borderColor: '#fff',
        elevation: 5,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 3 },
        shadowOpacity: 0.3,
        shadowRadius: 5,
    },
    nome: {
        fontSize: 24,
        fontFamily: "Poppins_700Bold",
        color: "#17285D",
        marginTop: 10,
    },
    email: {
        fontSize: 16,
        color: "#17285D",
        fontFamily: "Poppins_400Regular",
        marginTop: 2,
    },
    memberSince: {
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: 8,
        marginBottom: -30,
    },
    memberSinceText: {
        fontSize: 12,
        color: "#17285D",
        fontFamily: "Poppins_400Regular",
        marginLeft: 4,
    },
    section: {
        marginHorizontal: 20,
        marginBottom: 16,
        backgroundColor: "#fff",
        borderRadius: 20,
        padding: 20,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.1,
        shadowRadius: 12,
        elevation: 5,
        borderWidth: 1,
        borderColor: "rgba(0,0,0,0.05)",
    },
    memorySection: {
        borderLeftWidth: 4,
        borderLeftColor: "#17285D",
    },
    streakSection: {
        borderLeftWidth: 4,
        borderLeftColor: "#FF6B6B",
    },
    identitySection: {
        borderLeftWidth: 4,
        borderLeftColor: "#4ECDC4",
    },
    passwordSection: {
        borderLeftWidth: 4,
        borderLeftColor: "#45B7D1",
    },
    sectionHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 15,
    },
    sectionTitleContainer: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    sectionTitle: {
        fontSize: 18,
        fontFamily: "Poppins_700Bold",
        color: "#17285D",
        marginLeft: 8,
    },
    streakTitle: {
        color: "#FF6B6B",
    },
    memoryContent: {
        alignItems: 'center',
    },
    levelBadge: {
        backgroundColor: "#E3F2FD",
        paddingHorizontal: 20,
        paddingVertical: 8,
        borderRadius: 20,
        marginBottom: 15,
    },
    levelText: {
        fontSize: 16,
        fontFamily: "Poppins_700Bold",
        color: "#1976D2",
    },
    xpContainer: {
        alignItems: 'center',
        marginBottom: 15,
    },
    xpText: {
        fontSize: 24,
        fontFamily: "Poppins_700Bold",
        color: "#17285D",
    },
    nextLevelText: {
        fontSize: 12,
        fontFamily: "Poppins_400Regular",
        color: "#666",
        marginTop: 2,
    },
    progressBar: {
        width: '100%',
        height: 8,
        backgroundColor: "#E0E0E0",
        borderRadius: 4,
        marginBottom: 20,
        overflow: 'hidden',
    },
    progressFill: {
        height: '100%',
        backgroundColor: "#4CAF50",
        borderRadius: 4,
    },
    memoryStats: {
        flexDirection: 'row',
        justifyContent: 'space-around',
        width: '100%',
    },
    statItem: {
        alignItems: 'center',
    },
    statNumber: {
        fontSize: 20,
        marginBottom: 4,
    },
    statLabel: {
        fontSize: 12,
        fontFamily: "Poppins_500Medium",
        color: "#666",
    },
    streakPreview: {
        alignItems: 'center',
        paddingVertical: 10,
    },
    streakCount: {
        fontSize: 28,
        fontFamily: "Poppins_700Bold",
        color: "#FF6B6B",
    },
    streakSubtitle: {
        fontSize: 14,
        fontFamily: "Poppins_400Regular",
        color: "#666",
        marginTop: 4,
    },
    streakDetails: {
        marginTop: 15,
        paddingTop: 15,
        borderTopWidth: 1,
        borderTopColor: "#f0f0f0",
    },
    streakDetailItem: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 10,
    },
    streakDetailText: {
        fontSize: 14,
        fontFamily: "Poppins_400Regular",
        color: "#666",
        marginLeft: 8,
    },
    motivationText: {
        marginTop: 15,
        padding: 12,
        backgroundColor: "#FFF9C4",
        borderRadius: 10,
    },
    motivation: {
        fontSize: 14,
        fontFamily: "Poppins_700Bold",
        color: "#5D4037",
        textAlign: 'center',
    },
    identityContent: {
        marginTop: 10,
    },
    identityRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: 20,
    },
    identityItem: {
        flex: 1,
        alignItems: 'center',
        padding: 10,
    },
    identityLabel: {
        fontSize: 12,
        fontFamily: "Poppins_400Regular",
        color: "#666",
        marginTop: 4,
        marginBottom: 2,
    },
    identityValue: {
        fontSize: 14,
        fontFamily: "Poppins_700Bold",
        color: "#17285D",
    },
    identityQuote: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: "#F3E5F5",
        padding: 15,
        borderRadius: 12,
        marginTop: 10,
    },
    quoteText: {
        fontSize: 14,
        fontFamily: "Poppins_400Regular",
        color: "#7B1FA2",
        marginLeft: 8,
        fontStyle: 'italic',
        flex: 1,
    },
    securityBadge: {
        fontSize: 12,
        fontFamily: "Poppins_500Medium",
        color: "#4CAF50",
    },
    actions: {
        marginHorizontal: 20,
        marginBottom: 40,
        marginTop: 10,
    },
    button: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 15,
        paddingHorizontal: 30,
        borderRadius: 25,
        backgroundColor: "#5C172C",
    },
    logoutButton: {
        backgroundColor: "#5C172C",
    },
    buttonText: {
        color: "#fff",
        fontFamily: "Poppins_700Bold",
        fontSize: 16,
        marginLeft: 8,
    },
    placeholder: {
        fontStyle: "italic",
        color: "gray",
        textAlign: 'center',
        fontFamily: "Poppins_400Regular",
    },
    avatarsModalOverlay: {
        flex: 1,
        backgroundColor: "rgba(0,0,0,0.7)",
        justifyContent: "center",
        alignItems: "center",
        padding: 20,
    },
    avatarsModal: {
        width: "90%",
        backgroundColor: "#fff",
        borderRadius: 25,
        padding: 25,
        maxWidth: 400,
    },
    modalTitle: {
        fontSize: 22,
        fontFamily: "Poppins_700Bold",
        color: "#17285D",
        textAlign: 'center',
        marginBottom: 5,
    },
    modalSubtitle: {
        fontSize: 14,
        fontFamily: "Poppins_400Regular",
        color: "#666",
        textAlign: 'center',
        marginBottom: 20,
    },
    avatarsGrid: {
        flexDirection: "row",
        flexWrap: "wrap",
        justifyContent: "space-between",
    },
    avatarOption: {
        width: "48%",
        aspectRatio: 1,
        borderRadius: 20,
        overflow: "hidden",
        marginBottom: 15,
        borderWidth: 3,
        borderColor: "#e0e0e0",
    },
    avatarOptionImage: {
        width: "100%",
        height: "100%",
    },
    closeModalButton: {
        marginTop: 15,
        alignSelf: "center",
        paddingVertical: 12,
        paddingHorizontal: 30,
        backgroundColor: "#f5f5f5",
        borderRadius: 20,
    },
    closeModalText: {
        color: "#666",
        fontFamily: "Poppins_600SemiBold",
        fontSize: 16,
    },
});