import { StyleSheet, Dimensions } from "react-native";

const { width } = Dimensions.get("window");

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: "#fff",
    },
    scrollView: {
        flex: 1,
    },
    fixedHeader: {
        position: "absolute",
        top: 0,
        left: 0,
        right: 0,
        backgroundColor: "#fff",
        paddingTop: 50,
        paddingHorizontal: 20,
        paddingBottom: 15,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        zIndex: 1000,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 8,
        elevation: 5,
    },
    fixedBackButton: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: "#f5f5f5",
        alignItems: "center",
        justifyContent: "center",
    },
    fixedTitle: {
        flex: 1,
        fontSize: 16,
        fontFamily: "Poppins_700Bold",
        color: "#17285D",
        textAlign: "center",
        marginHorizontal: 10,
    },
    fixedPlaceholder: {
        width: 40,
    },
    heroImage: {
        width: "100%",
        height: 320, 
        justifyContent: "flex-end", 
    },
    heroOverlay: {
        ...StyleSheet.absoluteFillObject,
        backgroundColor: "rgba(0,0,0,0.4)",
    },
    backButton: {
        position: "absolute",
        top: 50,
        left: 20,
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: "rgba(0,0,0,0.5)",
        alignItems: "center",
        justifyContent: "center",
        zIndex: 10,
    },
    heroContent: {
        padding: 20,
        paddingBottom: 25,
    },
    categoryBadge: {
        alignSelf: "flex-start",
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 12,
        marginBottom: 12,
    },
    categoryText: {
        fontSize: 12,
        fontFamily: "Poppins_700Bold",
        color: "#17285D",
        textTransform: "uppercase",
    },
    title: {
        fontSize: 28,
        fontFamily: "Poppins_700Bold",
        color: "#fff",
        lineHeight: 34, 
        marginBottom: 15, 
        textShadowColor: "rgba(0,0,0,0.5)",
        textShadowOffset: { width: 1, height: 1 },
        textShadowRadius: 5,
    },
    metaContainer: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
    },
    authorContainer: {
        flexDirection: "row",
        alignItems: "center",
        flex: 1,
    },
    author: {
        fontSize: 14,
        fontFamily: "Poppins_600SemiBold",
        color: "rgba(255,255,255,0.9)",
        marginLeft: 6,
    },
    metaInfo: {
        flexDirection: "row",
    },
    metaItem: {
        flexDirection: "row",
        alignItems: "center",
        marginLeft: 12, 
    },
    metaText: {
        fontSize: 12,
        fontFamily: "Poppins_400Regular",
        color: "rgba(255,255,255,0.8)",
        marginLeft: 4,
    },
    content: {
        padding: 24,
        backgroundColor: "#fff",
    },
    contentHeader: {
        marginBottom: 24,
    },
    contentTitle: {
        fontSize: 22,
        fontFamily: "Poppins_700Bold",
        color: "#17285D",
        marginBottom: 12,
    },
    divider: {
        height: 3,
        backgroundColor: "#667eea",
        borderRadius: 2,
        width: 60,
    },
    text: {
        fontSize: 16,
        fontFamily: "Poppins_400Regular",
        color: "#444",
        lineHeight: 28,
        marginBottom: 24,
    },
    tipsSection: {
        backgroundColor: "#FFF9E6",
        padding: 20,
        borderRadius: 16,
        marginBottom: 24,
        borderLeftWidth: 4,
        borderLeftColor: "#FFD700",
    },
    tipsHeader: {
        flexDirection: "row",
        alignItems: "center",
        marginBottom: 12,
    },
    tipsTitle: {
        fontSize: 18,
        fontFamily: "Poppins_700Bold",
        color: "#5D4037",
        marginLeft: 8,
    },
    tipText: {
        fontSize: 14,
        fontFamily: "Poppins_400Regular",
        color: "#5D4037",
        lineHeight: 22,
    },
    ctaSection: {
        backgroundColor: "#f8fafc",
        padding: 24,
        borderRadius: 20,
        alignItems: "center",
        borderWidth: 2,
        borderColor: "#e1e5ef",
        borderStyle: "dashed",
    },
    ctaTitle: {
        fontSize: 20,
        fontFamily: "Poppins_700Bold",
        color: "#17285D",
        marginBottom: 8,
        textAlign: "center",
    },
    ctaText: {
        fontSize: 14,
        fontFamily: "Poppins_400Regular",
        color: "#666",
        textAlign: "center",
        marginBottom: 20,
        lineHeight: 20,
    },
    ctaButton: {
        backgroundColor: "#17285D",
        paddingHorizontal: 30,
        paddingVertical: 12,
        borderRadius: 25,
    },
    ctaButtonText: {
        fontSize: 16,
        fontFamily: "Poppins_600SemiBold",
        color: "#fff",
    },
    animation: {
        width: 230,
        height: 600,
        marginTop: -200,
        marginBottom: -150,
    },
    spacer: {
        justifyContent: 'center',
        alignItems: 'center',
    },
});